### ISSUE TITLE
US4: Follow a User

### ISSUE THREAD

**Issue by VictorTudoran** [samiha-rahman/SOEN341#11]
As a user, I want to be able to follow other users.

---------------------------------------------------------------------

**Tasks**

- [ ] 1. Create a follow button
- [ ] 2. See the lists: "following" and "followers" of a user
- [ ] 3. See the activity of "followed" users

------------------------------
**ACCEPTANCE TEST**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Login as a user and click on follow button under a user post | User is able to see followed user's posts | 
2 | Clicking on follow button | <Tail> button changes to <Un-leash> |
3 | Login as a user and click on unfollow button under a user post | User should no longer see unfollowed user's posts |
4 | Clicking on unfollow button | <Un-leash> button changes to <Tail> |

**Comment by davidchen2171** [comment]
Duplicated User Story
