### ISSUE TITLE
Edit user registration procedure and create new user role

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#15]
Providing a clean slate to build further features upon and simplify user registration

Tasks to be tracked: 
- [x] Remove email as a required field for new user creation #16 
- [x] Remove unnecessary roles #17 
- [x] Add "woofer" role #18 
- [x] Remove admin navigation bar for users of type “woofer” #19

**Comment by samiha-rahman** [comment]
All tasks related to this user story have been completed and merged to master.
