### ISSUE TITLE
Users can post woofs if they are logged in 

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#23]
Users should be able to post content if they are registered users and logged in.

Relevant user stories: 
- [x] Allow users to register #24 
- [x] Allow users to login #28 
- [x] Allow users to post woofs #32
