### ISSUE TITLE
Allow users to register

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#24]
Provide a UI on the front end to allow users to register.

Tasks to be tracked: 
- [x] Create a page template for user registration #25 
- [x] Handle user registration #26 
- [x] Automatic log in of new users #27

**Comment by samiha-rahman** [comment]
User story completed with pull request #39
