### ISSUE TITLE
Allow users to login

### ISSUE THREAD

**Issue by samiha-rahman** [samiha-rahman/SOEN341#28]
Provide a UI to allow users to login and access profile, post woofs, etc.

Tasks to be tracked: 
- [x] Create custom login form #29 
- [x] Create a page template for user login #30
- [x] Redirect to login form on failure #31
