### ISSUE TITLE
Prepare functions which handles follow/unfollow feature

### ISSUE THREAD

**Issue by davidchen2171** [samiha-rahman/SOEN341#60]
Task to be tracked:

- [x] Prepare PHP and JavaScript to communicate with AJAX #61  
- [x] JavaScript file which handles the AJAX call for following someone #62
- [x] Handle AJAX call on server side #63

------------------------------
**ACCEPTANCE TEST**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Login as a user and click on follow/unfollow button under a user post (Open Developer Tool on web browser) | Server should receive get method from AJAX |  PASSED
2 | Clicking on follow button | "Tail" button changes to "Un-leash" | PASSED
3| Clicking on unfollow button | "Un-leash" button changes to "Tail" | PASSED
