### ISSUE TITLE
Prepare functions from back-end to implement LIKE Feature

### ISSUE THREAD

**Issue by davidchen2171** [samiha-rahman/SOEN341#68]
Tasks to be tracked:

- [x]  Prepare PHP and JavaScript to communicate through AJAX [LIKE] #69
- [x]  JavaScript file which handles the AJAX call for liking a tweet. #70
- [x]  Handle the AJAX call on server side [LIKE].  #71

------------------------------
**ACCEPTANCE TEST**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Login and like a post (open developer tools on web browser)| Server should receive get method from AJAX (like) | PASSED
2 | Login and like\unlike a post | Like button (Bone) should be changed on-click | PASSED
3 | Login and like a post |  "Liked woofs" page should display all liked posts from user | PASSED

**Comment by samiha-rahman** [comment]
User story completed and acceptance tests passed.
