### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by davidchen2171** [samiha-rahman/SOEN341#75]
Improve the user interface design of the website.3

Tasks to follow:

- [x] UI Improvement: Navigation #100
- [x] UI Improvement: Logo #101
- [x] UI Improvement: Posts #102 
- [x] UI Improvement: Beautify Forms #103

------------------------------
**ACCEPTANCE TEST**

Step # | Execution Procedure or Input | Expected Results/Outputs | Passed/Failed
--- | --- | --- | ---
1 | Go to Login, Sign up page | UI for form should be changed  | PASSED
2 | Login and Go to Explore, Liked, Followed, Profile page | UI for posts should be changed  |  PASSED
3 | Go to profile page | UI for posting woofs should be changed  | PASSED
4 | Go to any page | Woofer logo should be displayed | PASSED
5 | Go to any page | Navbar UI should be changed, placed in top-left corner now | PASSED
6 | Go to any page | Font should be changed | PASSED

**Comment by davidchen2171** [comment]
Acceptance Test done
